### ISSUE TITLE
Aggiunto Gravina In Puglia e resi standard alcuni RSS

### ISSUE THREAD

**Issue by sputnik63** [ondata/albopopTwoDotZero#105]
Aggiunto Gravina In Puglia e resi standard gli RSS di Bitonto, Giovinazzo, Irsina, Modugno, Molfetta, Terlizzi.
Rielaborati i files script/data.csv, script/geodata.csv, script/geodata.json
Ho pronto il tutto in develop, merged con le ultime aggiunte fatte (es unioneterredimezzo) ma non riesco a fare la pull col mio account. Come posso procedere ?
Ancora una domanda. Nel tutorial è scritto di ricordarsi della cartella "public" che però non è sotto git. Cosa va fatto con la ./public ?
Grazie

**Comment by sputnik63** [comment]
Ho fatto un fork e una pull request.
Rimane la mia seconda domanda: cosa fare esattamente con i public ?

**Comment by aborruso** [comment]
@sputnik63 per favore mi scrivi qual è il tutorial a cui fai riferimento? Nel tempo ne sono usciti, e volendo risponderti per bene, vorrei partire da quello giusto.

Grazie

**Comment by sputnik63** [comment]
Parlavo della main page qui in gitHub. Il punto 6 del capitolo "Contribuisci" cita: 
> Salva le tue modifiche al progetto con git add . e git commit -m '[descrizione modifiche]' (assicurati di committare anche i file della cartella public/).

**Comment by aborruso** [comment]
Grazie @sputnik63 ho modificato il [testo](https://github.com/ondata/albopopTwoDotZero/commit/3518f33b6cb91db8a521779bbf89607a9758687a). Adesso non è più necessario
