### ISSUE TITLE
Il bottone "Scopri come si aderisce ufficialmente" non funziona

### ISSUE THREAD

**Issue by sputnik63** [ondata/albopopTwoDotZero#111]
Nella pagina dei comuni, il bottone "Scopri come si aderisce ufficialmente" posto sopra l'header "Le PA ufficialmente POP" non funziona.
Provato con Firefox e Chrome su Kubuntu Linux.

**Comment by aborruso** [comment]
Modificato, grazie

**Comment by sputnik63** [comment]
Ma non è stato ancora rilasciato ? Perché continua a non funzionare. Provato anche su Linux

**Comment by aborruso** [comment]
Ciao,
lo avevo modificato qui https://albopop.it/ufficiale/

Non avevo visto l'altro. Procedo

![image](https://user-images.githubusercontent.com/30607/68571021-41795c00-0462-11ea-8cc6-a0fdbb5fe0f5.png)

**Comment by aborruso** [comment]
Fatto, grazie ancora
