### ISSUE TITLE
Comune di Praia a Mare - problema al feed RSS

### ISSUE THREAD

**Issue by castellano88** [ondata/albopopTwoDotZero#126]
Buongiorno a tutti. Piccolo problema con il funzionamento dell'AlboPOP del Comune di Praia a Mare che proprio non ne vuole sapere di funzionare a dovere. 😅
Ho configurato tutto come previsto (foglio google, bot ifttt, Ifttt stesso) ma non parte la condivisione sul canale Telegram indicato. 
Andando sull'applet e cercando il registro delle attività mi compare il messaggio "applet failed" che credo dipenda nel 99% dei casi dal fatto che non c'è nulla di nuovo da pubblicare. 
Il problema è che qualcosa da pubblicare ci sarebbe!
E' un problema di IFTTT o dello scraper? 

Ecco il link del feed RSS: https://script.google.com/macros/s/AKfycbz3u9HG9Ztix1CbmPLNs2QY9HQWW5L22T0rL99sURsLA0urtuKg/exec

**Comment by aborruso** [comment]
Ciao @castellano88 ,
quando IFTTT non pubblica, di solito avviene per due ragioni: il feed non supera la [validazione](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fscript.google.com%2Fmacros%2Fs%2FAKfycbz3u9HG9Ztix1CbmPLNs2QY9HQWW5L22T0rL99sURsLA0urtuKg%2Fexec), oppure perché c'è una certa lentezza nel leggerlo.

Il feed è valido, quindi è probabile che la causa possa essere la seconda. I feed generati via script sono alle volte "lenti"; un modo per renderli più rapidi è crearne una copia con [feedburner](https://feedburner.google.com/).

Qui un videotutorial che spiega come si fa: https://www.youtube.com/watch?v=I6RdiJk2ZPk&feature=youtu.be&hd=1

Ti verrà generato un nuovo URL di feed RSS; usa questo nuovo con IFTTT.

Facci sapere

**Comment by castellano88** [comment]
Grazie mille per il video, ho seguito il procedimento indicato ed effettivamente IFTTT si è attivato incominciando ad inviare le varie pubblicazioni. E' necessario cambiare il link del feed RSS anche nel foglio utilizzato per lo scraping?
Ho, inoltre, rilevato un problema: il link di ogni atto pubblicato mi dà errore 404 (allego screen). 
![22222](https://user-images.githubusercontent.com/57262295/71029111-ff9d9e80-210e-11ea-8118-3a9bde5fe8b6.JPG)
Già in fase di scraping l'individuazione dell'href mi ha dato qualche grattacapo...mi chiedo: qeusto errore da cosa potrebbe dipendere? Ecco il file che ho utilizzato per lo scraping (https://docs.google.com/spreadsheets/d/10o8pm05U7W7QxY3e0s4VaeDonUX_sdjHcS8eThqr6vM/edit?usp=sharing)

Grazie mille in anticipo

**Comment by aborruso** [comment]
Ciao @castellano88 l'errore nell'URL è un piccolo errore umano. Se ne vedi uno

`http://albopraiaamare.asmenet.it/allegati.phpallegati.php?id_doc=17171206&sez=p&data1=17/12/2019&data2=01/01/2020`

vedrai che c'è due volte `allegati.php`. Quindi dovrai correggere la funzione che hai creato.

Qual è l'URL nuovo del feed?

**Comment by castellano88** [comment]
Eccolo qui http://feeds.feedburner.com/AlbopopPraiaAMare_enhanced

**Comment by aborruso** [comment]
@castellano88 tutto risolto?

**Comment by castellano88** [comment]
@aborruso si, oggi è entrato completamente in funzione l'alboPOP del Comune di Praia a Mare. Un altro da aggiungere alla lista!

**Comment by aborruso** [comment]
@castellano88 mi rispondi per favore a [questa](https://github.com/ondata/albopopTwoDotZero/issues/128#issue-541183270)?

Grazie
