### ISSUE TITLE
Aggiungere Comune di Praia a Mare

### ISSUE THREAD

**Issue by aborruso** [ondata/albopopTwoDotZero#128]
@castellan88 ha creato il feed del Comune di Praia a Mare (vedi #126 ): aggiungere a sito.

@castellanno88 mi rispondi a questa indicandomi:

- URL ufficiale albo;
- URL feed che hai creato;
- se hai creato canale Telegram, il nome del canale.

Grazie

**Comment by castellano88** [comment]
Ecco qui:
- http://albopraiaamare.asmenet.it (URL ufficiale)
- http://feeds.feedburner.com/AlbopopPraiaAMare_enhanced (URL feed)
- il nome del canale è @comunepraiaamare
