### ISSUE TITLE
Richiesta aiuto AlboPop Comune di Cori, non attivo dal 2020

### ISSUE THREAD

**Issue by milanini** [ondata/albopopTwoDotZero#130]
## Qual è la Pubblica Amministrazione per la quale cerchi una mano per creare l'AlboPOP?

Scrivi qui la risposta
per il Comune di Cori, l'albopop non è più attivo via Telegram , mi sembra anche il feedburner non più attivo: http://feeds.feedburner.com/AlbopopDelComuneDiCori
## Qual è l'URL dell'albo ufficiale?
Scrivi qui la risposta
https://albopretorio.datamanagementitalia.it/AlboPretorioWeb/?ente=ComuneDiCori&tipoSubmit=ricerca

## Che conoscenze di informatica hai?
Scrivi qui la risposta
elementare
---
Grazie in anticipo, e buon anno a tutti!

**NOTA BENE**: in questo spazio non c'è un addetto alla creazione di Albi POP, ma è possibile che qui tu possa trovare qualcuno che ti dia una mano nel farlo 🤞

**Comment by aborruso** [comment]
Ciao Antonella,
questo albo è di quelli senza singola pagina per atto e senza un URL da associare ad atto.

Quello che si può fare è un avviso testuale per ogni nuovo atto, ma con URL che riporta a homepage

**Comment by milanini** [comment]
Grazie Andrea e  buon anno,

se ho capito bene dal 2020 non vi è più l’url  di "appoggio intermedio” tra atto pubblico e singoli documenti che lo compongono, 
per cui non è possibile collegare  un feed al canale Telegram?

Quindi telegram andrebbe alimentato manualmente? 
L’assenza dell’Url  sarebbe un adempimento al GPDR?

**Comment by aborruso** [comment]
@milanini al momento c'è soltanto la lista e non la pagina intermedia.

Inoltre nemmeno i documenti hanno URL, ma devi fare un click e generare un popup, i cui a sua volta c'è l'URL dell'atto. Insomma è uno di quegli albi "lontani" dai cittadini e da un uso comodo.

Quello che possiamo fare è attivare un feed RSS, che si aggiorna per ogni nuovo atto, con il testo dell'atto e la sua categoria e con un link. Il link però riporterà alla home dell'albo.

Secondo me è comunque utile. Aspetto un tuo riscontro

**Comment by aborruso** [comment]
Ciao Antonella,
e prima di tutto buon anno anche a te.

Ho trovato una strana strada alternativa e ho riattivato il feed
<http://feeds.feedburner.com/AlbopopDelComuneDiCori>. La pubblicazione
automatica dovrebbe ripartire.

Ho visto che oggi avete aggiornato il canale. Lo avete fatto a mano?

Buona giornata


-- 
___________________

Andrea Borruso
website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E, EPSG:4326
___________________

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by milanini** [comment]
Buona domenica , Andrea
grazie tantissimo, ieri sì avevo iniziato ad alimentarlo  a mano, 
ed ora ho visto che  è ripartito,  la Strana Strada Alternativa è la tua Genialità,
e vorrei trovare il modo per farla riconoscere …

Grazie,  anche a nome di tutta la nostra Associazione Polygonal, in particolare dal Presidente Marco De Cave!

**Comment by milanini** [comment]
Gentile Andrea,

Grazie davvero per questa soluzione!

Credo aiuterà molto i tanti che leggono il canale!

Abbiamo la sensazione che sulla trasparenza ci sia così tanto ancora da
fare, ma le mentalità sono lente a muoversi.

Una domanda, inoltre, che ho è la seguente. Dal punto di vista del codice
dell'albopop riferito a Cori, dove si trova materialmente?

Abbiamo due ragazzi che studiano informatica e volevano darci un'occhiata
per vedere come funziona ed eventualmente contribuire, se possibile.

Ti ringrazio, di nuovo.

Un caro saluto e buon 2020.

**Comment by aborruso** [comment]
Ciao @milanini chiudo allora questa issue e ti rispondo in privato sul codice
