### ISSUE TITLE
Problema con Albo Pretorio San Giuseppe Jato - Feed ok ma non rilancia su canale telegram

### ISSUE THREAD

**Issue by giuragu** [ondata/albopopTwoDotZero#132]
Buongiorno,
ho un problema con l'AlboPOP di San Giuseppe Jato. Il feed RSS funziona. Ma non rilancia su telegram passando per IFTTT. Non è la prima volta. Ogni tanto faccio un reset della ricetta e sembra riprendere ma per pochissimo tempo. Adesso nonostante reset è fermo da giorni. Che fare?
Qui [feed e canale](https://albopop.it/comune/sangiuseppejato/)....

**Comment by aborruso** [comment]
@giuragu verifica che lo script su cui è basato, abbia associato un aggiornamento periodico.

In questo commento una mini guida video sul come fare https://github.com/ondata/albopopTwoDotZero/issues/131#issuecomment-582555974

**Comment by aborruso** [comment]
@giuragu puoi chiudere, se risolto?

**Comment by giuragu** [comment]
@aborruso scusaaaaa
