### ISSUE TITLE
Problema Albo Pretorio Comune di Rieti

### ISSUE THREAD

**Issue by marco-acorte** [ondata/albopopTwoDotZero#142]
il link ufficiale del comune di Rieti è cambiato:
- da http://albopretorio.insielmercato.it/AlboRieti/home.html
- a https://rieti-albo.palgpi.it/AlboRieti/home.html

nella pagina dedicata su https://albopop.it/comune/rieti/
il link del feed ress che punta a http://www.semplicepa.it/rssfeed/057059.xml risulta "not found" o con problemi tecnici

**Comment by aborruso** [comment]
Ciao @marco-acorte , grazie. 

C'è da ricostruire il motore. Speriamo di farlo a breve

**Comment by marco-acorte** [comment]
> Ciao @marco-acorte , grazie.
> 
> C'è da ricostruire il motore. Speriamo di farlo a breve

Io intanto faccio una PR per mettere a posto i link
