### ISSUE TITLE
impostare indentazione degli elenchi puntati

### ISSUE THREAD

**Issue by aborruso** [ondata/albopopTwoDotZero#19]
Al momento è così

![image](https://user-images.githubusercontent.com/30607/49665476-4b762c00-fa55-11e8-81e7-9d4987e8ae2f.png)

Da trasformare in

![image](https://user-images.githubusercontent.com/30607/49665503-621c8300-fa55-11e8-8006-d11ffc18c345.png)

**Comment by aborruso** [comment]
@jenkin ho fatto [questa modifica](https://github.com/ondata/albopopTwoDotZero/commit/7e2046cd95052bb5baba88f897eb79b962c0b2e4) ma non sono sicuro che sia la cosa giusta con scss. Se lo è, come si ribuilda il css di output?

**Comment by jenkin** [comment]
Fa tutto hugo...

**Comment by aborruso** [comment]
grazie
