### ISSUE TITLE
"Post recenti" è inserito due volte

### ISSUE THREAD

**Issue by aborruso** [ondata/albopopTwoDotZero#24]
Vedi http://dev.albopop.it/cc/

![image](https://user-images.githubusercontent.com/30607/49763699-aade7100-fccd-11e8-9eda-68c925cdd4d4.png)

**Comment by aborruso** [comment]
Se ne ha evidenza anche qui  in basso (stesso template) http://dev.albopop.it/chi-siamo/

**Comment by jenkin** [comment]
Credo fosse legato al problema del modulo del tema non aggiornato.
