### ISSUE TITLE
Al click sui tag non vengono listati gli item corrispondenti

### ISSUE THREAD

**Issue by aborruso** [ondata/albopopTwoDotZero#26]
Parlo di questi 

![image](https://user-images.githubusercontent.com/30607/49767042-47594100-fcd7-11e8-8c73-d8cdfedac1df.png)

**Comment by jenkin** [comment]
Questa è una roba che riguarda un layout di Hugo, sai qual è quello che si occupa del rendering delle pagine dei tag?

**Comment by jenkin** [comment]
Ho eliminato il link...
