### ISSUE TITLE
cover gruppo fb

### ISSUE THREAD

**Issue by aborruso** [ondata/albopopTwoDotZero#27]

**Comment by Jaaapiii** [comment]
Ecco qui!
Semplice semplice, se vi piace usiamola, altrimenti avanti con le idee 🤓

![facebook group cover](https://user-images.githubusercontent.com/18459582/49965791-7ad9dc80-ff1e-11e8-8b3e-3fb8744f4342.png)

**Comment by aborruso** [comment]
Ottimo grazie!
