### ISSUE TITLE
Scrivere blog post RT

### ISSUE THREAD

**Issue by aborruso** [ondata/albopopTwoDotZero#39]
Caro @lorenzoperone lo scrivi per favore il testo per [questo post](http://dev.albopop.it/post/come-albopop-puo-aiutare-i-cittadini-colpiti-dal-terremoto/)?

Se vuoi, anche direttamente in markdown, modificando [questo](https://github.com/ondata/albopopTwoDotZero/blob/develop/content/post/come-albopop-puo-aiutare-i-cittadini-colpiti-dal-terremoto.md).

Grazie

**Comment by aborruso** [comment]
Qui URL, avevo dimenticato http://dev.albopop.it/post/come-albopop-puo-aiutare-i-cittadini-colpiti-dal-terremoto/

**Comment by lorenzoperone** [comment]
@aborruso ho comiittato la prima bozza, ha una lunghezza adeguata oppure il tema va sviluppato più approfonditamente?

**Comment by aborruso** [comment]
@lorenzoperone va bene grazie
