### ISSUE TITLE
Aggiungere l'output json anche per le pagine dei singoli comuni

### ISSUE THREAD

**Issue by jenkin** [ondata/albopopTwoDotZero#40]
Abbiamo il [json con tutti gli albi](http://dev.albopop.it/comuni-pa/index.json) (un array di oggetti), dovrebbe essere facile far generare il json (un solo oggetto) del singolo albo associato all'url http://dev.albopop.it/comune/[nome comune]/index.json.

**Comment by aborruso** [comment]
https://forestry.io/blog/build-a-json-api-with-hugo/

**Comment by jenkin** [comment]
Esempio: http://dev.albopop.it/comune/patti/index.json

**Comment by aborruso** [comment]
Mi piace molto!
