### ISSUE TITLE
icona tonda per twitter

### ISSUE THREAD

**Issue by aborruso** [ondata/albopopTwoDotZero#43]
@Jacoposolmi serve anche un'icona "tonda" per il profilo twitter

Io ci metterei questa, ma la scelta è bene che la faccia tu.

Grazie

![image](https://user-images.githubusercontent.com/30607/50013048-6bab6b00-ffc0-11e8-8d4f-d743532f44d1.png)

**Comment by Jaaapiii** [comment]
sìsì direi che va benissimo quella per il profilo, 
faccio una cover anche per twitter come quella del gruppo facebook, arrivo! 👍

**Comment by Jaaapiii** [comment]
Cover twitter:
![cover twitter](https://user-images.githubusercontent.com/18459582/50014745-0efe7f00-ffc5-11e8-9245-65d6fc25ed31.png)
Profile twitter:
![profile twitter](https://user-images.githubusercontent.com/18459582/50014747-0efe7f00-ffc5-11e8-9e89-6bd7b8ccbe17.png)

**Comment by aborruso** [comment]
grazie mille
