### ISSUE TITLE
Mappa interattiva da rifare

### ISSUE THREAD

**Issue by jenkin** [ondata/albopopTwoDotZero#5]
Al momento è stata inclusa la [pagina del sito originale](http://dev.albopop.it/mappa/) con una mappa interattiva basata su uMap che prende i dati da un [google spreadsheet](http://spreadsheets.google.com/tq?tqx=out:csv&tq=select%20A%2CB%2CC%2CD&key=1a-XlQl6jHxsHuemPEMLCEz9qekFnLr_-bfqnhBOwdvc&gid=1311822177&ttl=&oq=http://spreadsheets.google.com/tq?tqx=out:csv&tq=select%20A%2CB%2CC%2CD&key=1a-XlQl6jHxsHuemPEMLCEz9qekFnLr_-bfqnhBOwdvc&gid=1311822177&ttl=&aqs=chrome..69i57.170j0j7&sourceid=chrome&ie=UTF-8).

Ora che abbiamo un [json](http://dev.albopop.it/comuni-pa/index.json) compilato automaticamente dalle pagine dei comuni e delle altre pa del sito, sarebbe da reimplementare la mappa prendendo i dati da lì.

**Comment by jenkin** [comment]
Eccola, basata su [LeafletJS](https://leafletjs.com/): http://dev.albopop.it/mappa/.

**Comment by aborruso** [comment]
@jenkin la mappa non la visualizzo. 

Ho perso un tempo stupido e ho creato una nuova [fonte dati](https://github.com/ondata/albopopTwoDotZero/tree/develop/script) inutile (perché c'è il json nativo) e pure uno script. E la mappa è qui http://umap.openstreetmap.fr/it/map/albopop-20_274859

**Comment by jenkin** [comment]
Non la vedi perché si è rotto qualcosa... :(

**Comment by jenkin** [comment]
Mah, qualcuno aveva una vecchia versione del submodule del tema e aveva fatto una build in cui sono saltate alcune cose tra cui la mappa. @aborruso fai un check e dai un `git submodule update` nel tuo repo locale.

**Comment by aborruso** [comment]
@jenkin scusami :(
