### ISSUE TITLE
Attivare rigenerazione periodica del sito

### ISSUE THREAD

**Issue by aborruso** [ondata/albopopTwoDotZero#53]
Questo per avere un refresh di contenuti come quelli "Nella stessa regione", in modo che non sia sempre lo stesso elenco

**Comment by jenkin** [comment]
Oppure far generare quella lista lato client via javascript con un workaround furbetto...

**Comment by aborruso** [comment]
Attivata rigenerazione ogni ora, tramite gli hook di netlify

![image](https://user-images.githubusercontent.com/30607/53022287-2ccfe080-345b-11e9-90c7-7c33a3f6ab79.png)
