### ISSUE TITLE
Errore di battitura 

### ISSUE THREAD

**Issue by simoneversienti** [ondata/albopopTwoDotZero#63]
Buongiorno a tutti :smile: 

Volevo solo segnalare un piccolo errore di battitura per la parola "Comune" nella sezione [Comuni e altre PA](https://albopop.it/comuni-pa/), poco prima dell'elenco.

> Molti comuni sono stati resi Pop grazie al lavoro di attivisti che hanno scritto e mantengono piccoli software in grado di produrre un feed RSS dalla pagina statica del sito del COMMUNE. Ecco quali sono. 

Buon lavoro a tutti!

**Comment by aborruso** [comment]
grazie @simoneversienti
