### ISSUE TITLE
Pagina di riepilogo del blog

### ISSUE THREAD

**Issue by jenkin** [ondata/albopopTwoDotZero#7]
Non prevista nel mockup originale, come [la miglioriamo](http://dev.albopop.it/post/)?

**Comment by Jaaapiii** [comment]
Proporrei semplicemente...
![blog](https://user-images.githubusercontent.com/18459582/49363543-3b232180-f6e2-11e8-94f0-6802b67e724f.png)


Cosa ne pensate?

**Comment by Jaaapiii** [comment]
chiedo scusa @jenkin ma temo di doverti chiedere indicazioni su quale sia la pagina all'interno del progetto sulla quale lavorare. Non riesco ad individuarla con certezza e non vorrei sbagliare.

**Comment by jenkin** [comment]
@Jacoposolmi direi il file [layouts/partials/list-item.html](https://github.com/ondata/albopopTwoDotZero/blob/develop/layouts/partials/list-item.html). Occhio che quello fa il rendering anche del singolo elemento dell'[elenco degli albi](http://dev.albopop.it/comuni-pa/), quindi per mostrare l'excerpt devi mettere un if da qualche parte (sul .Type, per esempio, che sia solo "post").
