### ISSUE TITLE
incorporato video del webinar

### ISSUE THREAD

**Issue by nelsonmau** [ondata/albopopTwoDotZero#71]
ma non sono sicuro che sia ok

https://github.com/ondata/albopopTwoDotZero/commit/05a35ed8097d7ac0f99e5e4317b98c67328b77ef

l'html si include `as is` oppure c'è qualche superjancaxiola?

**Comment by aborruso** [comment]
caro @nelsonmau per farlo per bene, è meglio usare lo [hugo shortcode](https://gohugo.io/content-management/shortcodes/) per youtube.


Fatto qui: https://github.com/ondata/albopopTwoDotZero/commit/3870ea25967c5c54eb13ac21b6fcfb69a2202a37
