### ISSUE TITLE
IFTTT da RSS-AlboPop a FacebookPage triggera continuamente

### ISSUE THREAD

**Issue by lucasccrema** [ondata/albopopTwoDotZero#74]
Siccome nel mio Comune si usa molto facebook e poco Telegram, ho pensato di collegare IFTTT ad una pagina facebook ad hoc che poi qualsiasi cittadino può "seguire" per ricevere notifiche dall'Albopop. (https://www.facebook.com/pg/Albopop-Crema-332899054247863/posts/). Il problema è che vengono caricate continuamente le stesse cose e dopo un po', giustamente , IFFFT disattiva l'applet. Dove sbaglio?

**Comment by aborruso** [comment]
Ciao @lucasccrema , il trigger da RSS  si attiva per il cambio di URL/guid.

Nel tuo RSS gli URL sono fatti così

`http://.../web/trasparenza/papca-ap/-/papca/display/3793274?p_auth=eIu6c5MY&p_p_state=pop_up`

L'univocità sopra è data da `3793274`. La parte `p_auth=eIu6c5MY` è qualcosa di legata alla sessione e quindi diciamo che varia in base all'accesso. Allora puoi avere che la stessa notizia con ID `3793274` sia triggherata due volte, perché cambia la parte `p_auth`.

Devi fare quindi pulizia degli URL e rimuovere ciò che non serve. In questo caso diventerebbe:
http://crema.trasparenza-valutazione-merito.it/web/trasparenza/papca-ap/-/papca/display/3793274

Quindi ti basta usare una funzione che sfrutta le espressioni regolari (come REGREPLACE) e rimuovere quello che non serve dall'URL

**Comment by lucasccrema** [comment]
grazie
