### ISSUE TITLE
IFTTT RSS-AlboPOP a FacebookPage salta alcuni item

### ISSUE THREAD

**Issue by lucasccrema** [ondata/albopopTwoDotZero#75]
Non tutti gli item del feed RSS dell'AlboPOP (*) vengono inviati da IFTTT a FacebookPage (**) , ne mancano parecchi. Qualche suggerimento? Grazie in anticipo.

(*) https://script.googleusercontent.com/macros/echo?user_content_key=nocCnBKmQCK_GVB8V803X8jOtqsOM6aPAEgtva-ffQT96Lcj_m7qLPyQmke-wt5L55njDP3MkV1wj12jZnIwN3Nz5ixemA3xm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnPlcxsZeAlbjZ9bpyoFG87FSH54-yXa7sv0elf_nGs_ewtHBnTAr6C28mzDTCqnGIg&lib=MwTtM1fYkupkTduWF1fAPjX_8p-fAkEuh 

(**) https://www.facebook.com/pg/Albopop-Crema-332899054247863/posts

**Comment by aborruso** [comment]
Ciao @lucasccrema , è una cosa che dipende IFTTT.

Devi verificare nei log di IFTTT e vedere se ci sono degli errori. E in ogni caso scrivere al loro supporto ("salve nel feed RSS c'era ad esempio l'item ...., ma non è stato pubblicato").

Quindi purtroppo qui la issue la chiuderei

**Comment by lucasccrema** [comment]
Capito. Grazie!
