### ISSUE TITLE
AlboPOP a Torre Santa Susanna adottato ufficialmente

### ISSUE THREAD

**Issue by simoneversienti** [ondata/albopopTwoDotZero#83]
Buonasera a tutti :smile: 
Apro questa issue per comunicare un cambiamento di "stato" per il Comune di Torre Santa Susanna. 
Oggi, in giunta, è stato ufficialmente adottato AlboPOP (vi lascio [qui](http://dgegovpa.it/TorreSantaSusanna/albo/dati/20190087G.PDF) la determina), per cui credo debba essere spostato nella sezione "ufficiale".

Grazie a tutti in anticipo.

**Comment by aborruso** [comment]
Caro @simoneversienti una bella notizia!

A breve allora lo spostiamo e te ne do evidenza qui, complimenti

**Comment by simoneversienti** [comment]
Grazie mille ma complimenti a voi

**Comment by aborruso** [comment]
Eccolo qui in elenco :)

https://albopop.it/ufficiale/
