### ISSUE TITLE
Albo Pretorio Bagheria: incongruenza nella data di pubblicazione

### ISSUE THREAD

**Issue by zerai** [ondata/albopopTwoDotZero#84]
Il [feed](http://feeds.feedburner.com/BagheriaAlboPretorio) è attivo, ed il contenuto aggiornato, il problema riguarda la data di pubblicazione (attributo xml) presente nei singoli item, tale data risulta 3 mesi avanti.

Nello specifico, alla data di oggi 07 luglio 2019
tutti i singoli feed item riportano la data come segue:
Posted:Thu, 07 Nov 2019 11:00:00 +0000

**Comment by aborruso** [comment]
Grazie. Ci guardo e torno qui

**Comment by aborruso** [comment]
Dovrebbe essere ok adesso.

![image](https://user-images.githubusercontent.com/30607/61068628-c6982a00-a40a-11e9-9e8b-946e50950ad5.png)

Se per te ok, chiudi tu la issue
