### ISSUE TITLE
Albo Pretorio Castel Maggiore: incongruenza nella data di pubblicazione

### ISSUE THREAD

**Issue by zerai** [ondata/albopopTwoDotZero#85]
Il [feed](http://feeds.feedburner.com/AlbopopCastelMaggiore) è attivo, ed il contenuto aggiornato, il problema riguarda la data di pubblicazione (attributo xml) presente nei singoli item, tale data risulta 1 gennaio 1970
Nello specifico, alla data di oggi 14 luglio 2019
tutti i singoli feed item riportano la data come segue:
Posted:Thu, 01 Jan 1970 00:00:00 +0000

**Comment by aborruso** [comment]
ciao @zerai grazie.

Ho fatto una modifica. Come sempre fai per favore il check tu e nel caso chiudi?

**Comment by zerai** [comment]
La data ora è corretta, grazie @aborruso

**Comment by zerai** [comment]
Perdonami ho chiuso l'issue dopo aver visto la data dell'anno non più al 1970,
cmq. il software di monitoring mi continua a segnalare errore, effettivamente ora la data è al futuro,
dicembre 2019.
Posted:Sat, 07 Dec 2019 11:00:00 +0000

**Comment by aborruso** [comment]
@zerai dovrebbe essere ok

![image](https://user-images.githubusercontent.com/30607/61185610-aca15600-a65b-11e9-9356-c7a9b4072f50.png)
