### ISSUE TITLE
Feed url non presente in alcune pagine

### ISSUE THREAD

**Issue by zerai** [ondata/albopopTwoDotZero#88]
Ciao,
nelle seguenti pagine ci sono i link twitter/telegram, ma non è presente il link al feed rss.
[pagina Comune di Potenza](https://albopop.it/comune/potenza/)
[pagina Comune di Surbo](https://albopop.it/comune/surbo/)
[pagina Comune di Trabia](https://albopop.it/comune/trabia/)

**Comment by aborruso** [comment]
@piersoft puoi scrivere (anche qui) gli URL dei feed RSS dei tre comuni?

E grazie @zerai

**Comment by piersoft** [comment]
http://feeds.feedburner.com/Newspopsurbo

Gli altri non li ho io. 

Piersoft
Inviato da iPhone

**Comment by aborruso** [comment]
@piersoft grazie.

Per Trabia e Potenza a chi potrei chiedere?
Lo chiedo a te, perché in anagrafica risulti l'autore, ma magari hai collaborato con altri.

**Comment by piersoft** [comment]
Andrea, per Potenza fui io ma cessai il bot.

Trabia non so cosa sia

Il giorno mer 17 lug 2019 alle ore 13:03 Andrea Borruso <
notifications@github.com> ha scritto:

**Comment by aborruso** [comment]
Grazie @piersoft ho inserito il feed.

E ho messo in draft gli altri due
