### ISSUE TITLE
Sidebar con gli ultimi post e le tag

### ISSUE THREAD

**Issue by jenkin** [ondata/albopopTwoDotZero#9]
Al momento nelle pagine singole semplici ([esempio](http://dev.albopop.it/faq/)), nelle pagine di singolo post ([esempio](http://dev.albopop.it/post/2015-12-15-a-san-giuseppe-jato-il-i-albo-pop-happy-hour/)) e in quelle di singolo albo ([esempio](http://dev.albopop.it/comune/bitonto/)) è inclusa una sidebar con gli ultimi post e le etichette usate.

Non era prevista nel mockup. Se la lasciamo bisogna sistemarne l'aspetto, se la togliamo mi sembra che in alcuni casi il testo del contenuto si davvero troppo scarno per *riempire* efficacemente la pagina.

![screenshot_20181128_181126](https://user-images.githubusercontent.com/426495/49168977-09eccf00-f339-11e8-99e5-e3dfbdc7b20b.png)

**Comment by Jaaapiii** [comment]
Per quanto riguarda quella presente nella pagina singolo Albo, potremmo usare la sidebar per elencare alcuni Comuni con le caratteristiche simili? tipo che siano della stessa provincia/regione? Oppure con i tag condivisi.
Cosa ne pensate?

La sidebar è necessario che sia uguale nelle pagine che hai elencato?

**Comment by jenkin** [comment]
Confermo che si può cambiare il contenuto della sidebar a seconda del tipo di pagina in cui viene inclusa e quindi per il singolo albo possiamo elencare quelli della stessa provincia / regione / tag.

Per gli altri tipi di pagina (pagine singole, singolo post del blog)?

**Comment by jenkin** [comment]
Fatto, ora nelle pagine di singolo comune ci sono due blocchi contestuali: i comuni della stessa regione e i comuni con gli stessi tag. Eventualmente stile e struttura si cambiano nei partial "recent" e "nearest".

**Comment by aborruso** [comment]
@jenkin molto bene, mi piace. Quando saranno tanti si dovranno mettere forse 5 random

**Comment by jenkin** [comment]
@aborruso veramente sono proprio 5 random... :laughing:

**Comment by aborruso** [comment]
Amen
