### ISSUE TITLE
Modificare feed Comune di San Giuseppe Jato

### ISSUE THREAD

**Issue by giuragu** [ondata/albopopTwoDotZero#95]
Ci sarebbe da modificare il feed RSS del Comune di San Giuseppe Jato indicato [qui](https://albopop.it/comune/sangiuseppejato/) in http://feeds.feedburner.com/AlbopretorioSanGiuseppeJato

Inoltre cancellare riferimento al canale twitter
@aborruso che mi dici?

**Comment by aborruso** [comment]
Caro @giuragu ,
cerca San Giuseppe qui [albopopTwoDotZero/content/comune](https://github.com/ondata/albopopTwoDotZero/tree/develop/content/comune) e poi fai la modifica.

Le parti da cambiare sono quelle tra `---`, che sono le uniche che finiscono online.

Mettiti tra gli autori, con la stessa formattazione che vedi ad esempio [qui](https://raw.githubusercontent.com/ondata/albopopTwoDotZero/97bd4317da5bd61cb8449c3c5b10e721611276a7/content/altrepa/unict.md).

Fammi sapere

![image](https://user-images.githubusercontent.com/30607/66458287-a6602180-ea72-11e9-9430-368e0a19c377.png)

**Comment by giuragu** [comment]
Grazie mille @aborruso.
[Fatto](https://albopop.it/comune/sangiuseppejato/). Passo e chiudo
